src/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),

    # Employee
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:id>/',
         views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',
         views.employee_edit_data, name='edit'),
    path('employee/profile/delete/<int:id>/',
         views.dashboard_employee_delete, name='delete'),
    # Departement
    path('departments/all/', views.dashboard_departments, name='departments'),
    path('department/create/', views.dashboard_department_create,
         name='departmentcreate'),
    path('department/edit/<int:id>/',
         views.dashboard_department_edit_data, name='departmentedit'),
    path('department/delete/<int:id>/',
         views.dashboard_department_delete, name='departmentdelete'),
    # Role
    path('roles/all/', views.dashboard_roles, name='roles'),
    path('role/create/', views.dashboard_role_create, name='rolecreate'),
    path('role/edit/<int:id>/', views.dashboard_role_edit_data, name='roleedit'),
    path('role/delete/<int:id>/', views.dashboard_role_delete, name='roledelete'),

    # Announcement
    path('announcements/all/', views.dashboard_announcements, name='announcements'),
    path('announcement/create/', views.dashboard_announcement_create,
         name='announcementcreate'),
    path('announcement/edit/<int:id>/',
         views.dashboard_announcement_edit_data, name='announcementedit'),
    path('announcement/delete/<int:id>/',
         views.dashboard_announcement_delete, name='announcementdelete'),
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views


urlpatterns = [
    # change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('admin/', admin.site.urls),
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'PFA ADMINISTRATION'

src/dashboard/models.py
from django.db import models

# Create your models here.

src/dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from employee.forms import EmployeeCreateForm, DepartmentCreateForm, RoleCreateForm, AnnouncementCreateForm
from employee.models import *


def dashboard(request):
    dataset = dict()
    user = request.user

    if not request.user.is_authenticated:
        return redirect('accounts:login')

    employees = Employee.objects.all()
    departments = Department.objects.all()
    roles = Role.objects.all()

    dataset['employees'] = employees
    dataset['departments'] = departments
    dataset['roles'] = roles
    dataset['title'] = 'summary'

    return render(request, 'dashboard/dashboard_index.html', dataset)


########################################################## EMPLOYEE ##########################################################

# ALL EMPLOYEES
def dashboard_employees(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    dataset = dict()
    departments = Department.objects.all()
    employees = Employee.objects.all()

    # pagination
    query = request.GET.get('search')
    if query:
        employees = employees.filter(
            Q(firstname__icontains=query) |
            Q(lastname__icontains=query)
        )

    paginator = Paginator(employees, 10)  # show 10 employee lists per page

    page = request.GET.get('page')
    employees_paginated = paginator.get_page(page)

    dataset['employee_list'] = employees_paginated
    dataset['departments'] = departments
    dataset['all_employees'] = Employee.objects.all_employees()

    dataset['title'] = 'Employees list view'
    return render(request, 'dashboard/employee_app.html', dataset)

# CREATE EMPLOYEE


def dashboard_employees_create(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    if request.method == 'POST':
        form = EmployeeCreateForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            user = request.POST.get('user')
            assigned_user = User.objects.get(id=user)

            instance.user = assigned_user

            instance.title = request.POST.get('title')
            instance.image = request.FILES.get('image')
            instance.firstname = request.POST.get('firstname')
            instance.lastname = request.POST.get('lastname')
            instance.othername = request.POST.get('othername')
            instance.sex = request.POST.get('sex')
            instance.bio = request.POST.get('bio')
            instance.birthday = request.POST.get('birthday')

            department_id = request.POST.get('department')
            department = Department.objects.get(id=department_id)
            instance.department = department

            instance.position = request.POST.get('position')
            instance.ssnitnumber = request.POST.get('cinnumber')

            role = request.POST.get('role')
            role_instance = Role.objects.get(id=role)
            instance.role = role_instance

            instance.startdate = request.POST.get('startdate')
            instance.employeetype = request.POST.get('employeetype')

            instance.save()

            return redirect('dashboard:employees')
        else:
            messages.error(request, 'Trying to create dublicate employees with a single user account ',
                           extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:employeecreate')

    dataset = dict()
    form = EmployeeCreateForm()
    dataset['form'] = form
    dataset['title'] = 'register employee'
    return render(request, 'dashboard/employee_create.html', dataset)

# EDIT EMPLOYEE


def employee_edit_data(request, id):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')
    employee = get_object_or_404(Employee, id=id)
    if request.method == 'POST':
        form = EmployeeCreateForm(
            request.POST or None, request.FILES or None, instance=employee)
        if form.is_valid():
            instance = form.save(commit=False)

            user = request.POST.get('user')
            assigned_user = User.objects.get(id=user)

            instance.user = assigned_user

            instance.title = request.POST.get('title')
            instance.image = request.FILES.get('image')
            instance.firstname = request.POST.get('firstname')
            instance.lastname = request.POST.get('lastname')
            instance.othername = request.POST.get('othername')
            instance.sex = request.POST.get('sex')
            instance.bio = request.POST.get('bio')
            instance.birthday = request.POST.get('birthday')

            department_id = request.POST.get('department')
            department = Department.objects.get(id=department_id)
            instance.department = department

            instance.position = request.POST.get('position')
            instance.ssnitnumber = request.POST.get('cinnumber')

            role = request.POST.get('role')
            role_instance = Role.objects.get(id=role)
            instance.role = role_instance

            instance.startdate = request.POST.get('startdate')
            instance.employeetype = request.POST.get('employeetype')

            instance.save()
            messages.success(request, 'Account Updated Successfully !!!',
                             extra_tags='alert alert-success alert-dismissible show')
            return redirect('dashboard:employees')

        else:

            messages.error(request, 'Error Updating account',
                           extra_tags='alert alert-warning alert-dismissible show')
            return HttpResponse("Form data not valid")

    dataset = dict()
    form = EmployeeCreateForm(request.POST or None,
                              request.FILES or None, instance=employee)
    dataset['form'] = form
    return render(request, 'dashboard/employee_create.html', dataset)

# EMPLOYEE DETAILS


def dashboard_employee_info(request, id):
    if not request.user.is_authenticated:
        return redirect('/')

    employee = get_object_or_404(Employee, id=id)

    dataset = dict()
    dataset['employee'] = employee
    return render(request, 'dashboard/employee_detail.html', dataset)

# DELETE EMPLOYEE


def dashboard_employee_delete(request, id):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    employee = get_object_or_404(Employee, id=id)
    employee.delete()
    return redirect('dashboard:employees')

########################################################## DEPARTMENT ##########################################################
# ALL DEPARTMENTS


def dashboard_departments(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')
    dataset = dict()
    departments = Department.objects.all()

    query = request.GET.get('search')
    if query:
        departments = departments.filter(
            Q(name__icontains=query)
        )

    paginator = Paginator(departments, 10)  # show 10 employee lists per page

    page = request.GET.get('page')
    departments_paginated = paginator.get_page(page)

    dataset['department_list'] = departments_paginated
    dataset['title'] = 'departments'
    dataset['departments'] = Department.objects.all()
    return render(request, 'dashboard/departments.html', dataset)

# CREATE DEPARTMENT


def dashboard_department_create(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    if request.method == 'POST':
        form = DepartmentCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = request.POST.get('name')
            instance.save()
            return redirect('dashboard:departments')
        else:
            messages.error(request, 'Trying to create dublicate department',
                           extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:departmentcreate')

    dataset = dict()
    form = DepartmentCreateForm()
    dataset['form'] = form
    dataset['title'] = 'register department'
    return render(request, 'dashboard/department_create.html', dataset)

# EDIT DEPARTMENT


def dashboard_department_edit_data(request, id):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    department = get_object_or_404(Department, id=id)
    if request.method == 'POST':
        form = DepartmentCreateForm(request.POST, instance=department)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = request.POST.get('name')
            instance.save()
            return redirect('dashboard:departments')
        else:
            messages.error(request, 'Trying to create dublicate department',
                           extra_tags='alert alert-warning alert-dismissible show')
            return redirect('dashboard:departmentcreate')

    dataset = dict()
    form = DepartmentCreateForm(request.POST or None, instance=department)
    dataset['form'] = form
    dataset['title'] = 'edit - {0}'.format(department.name)
    return render(request, 'dashboard/department_create.html', dataset)

src/templates/dashboard/announcements.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}


 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 <!-- width:200px; --><!-- enabled -> removes box responsiveness : avoid this -->
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #60a0b3 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#60a0b3;
}





{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	<section class="row">
	            		<section class="col col-lg-12">
	            			<a href="{{request.META.HTTP_REFERER|escape}}" style="color:#c1c1c1;">back</a>
	            		</section>
            	</section>
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
                    <!-- <div class="container"> -->
						<section class="row margin-bottom">
							<div class="container-fluid">
							<section class="col-lg-4 col-md-4 col-sm-12">
								<div class="leave-box sec-box">
									<a href="{% url 'dashboard:announcements' %}">
									<span>Announcement</span>
									</a>
									<span class="count-object deprt">{{ announcements.count }}</span>
								</div>
							</section>
							</div>
						</section><!-- /row --><!-- /row -->

                    <!-- </div> -->
                    <!-- Search form -->
					<div class="row" style="margin-bottom: 2.2rem;margin-top: 3rem;">
					 <div class="">
					  <div class="col-lg-12">

					  	<form action="" method="GET">
						    <div class="input-group">
						      <span class="input-group-btn">
						        <button class="btn btn-default" id = "stylebutton" type="button">Search</button>
						      </span>
						      <input type="search" value="{{request.GET.search}}" name="search" class="form-control" placeholder="Search by Name">
						    </div><!-- /input-group -->
					    </form>

					  </div><!-- /.col-lg-6 -->
					  </div>
					</div><!-- /.row -->
					<!-- /search form -->

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">ALL Announcement TABLE</h4>
                		</div>
                		<div class="container-fluid">
                			<div class="row">
                			</div>
                		</div>
                		<table class="table">
							  <thead>
							    <tr>
							      <th scope="col">Name</th>
								  <th scope="col">Description</th>
								  {% if request.user.is_superuser and request.user.is_staff %}

								  <th scope="col">Actions</th>
								  {% endif %}
							    </tr>
							  </thead>
							  <tbody>
							  	{% for announcement in announcement_list %}
							    <tr>

							      <td>{{ announcement.name }}</td>		
							      <td>{{ announcement.bio }}</td>																	
							      <td> 		      	
							{% if request.user.is_superuser and request.user.is_staff %}

							<a href="{% url 'dashboard:announcementedit' announcement.id %}">
							       	edit
							        </a>
									<a href="{% url 'dashboard:announcementdelete' announcement.id %}">
										delete
									 </a> 
							      </td>
							    </tr>
							{% endif %}
							{% endfor %}

							  </tbody>
						</table>
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

src/templates/dashboard/dashboard_index.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}
{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}
  {% block stylesheet %}
     .sec-box{
     <!-- width:400px; --><!-- dont uncomment this code - line -->
     height:160px;
     max-width:100%;
     line-height:160px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
 }

.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#41b6d6;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.company-box{
	background:#868686;
}


.count-object {
    position: absolute;
    top: 40%;
    right: 12px;
    font-size: 29px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}


     
  {% endblock %}

  

 <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	<section class="row">
            		{% if request.user.is_superuser and request.user.is_staff %}
            		<section class="col col-lg-4">
            			<div class="employee-box sec-box">
            				<a href="{% url 'dashboard:employees' %}">
            				<span>Employees </span>
            				</a>
            				<span class="count-object">{{ employees.count }}</span> 
            			</div>
            		</section>
                    <section class="col col-lg-4">
            			<div class="employee-box sec-box">
            				<a href="{% url 'dashboard:departments' %}">
            				<span>Departments </span>
            				</a>
                            <span class="count-object deprt">{{ departments.count }}</span>
            			</div>
            		</section>
                    <section class="col col-lg-4">
            			<div class="employee-box sec-box">
            				<a href="{% url 'dashboard:roles' %}">
            				<span>Roles </span>
            				</a>
            				<span class="count-object">{{ roles.count }}</span> 
            			</div>
            		</section>
                    {% endif %}
            	</section>
            </section> <!-- /container -->           
        </section>
 {% endblock %}


{% block extrajs%}
    
    

    $(document).ready(function(){
          var get_login_user = '{{request.user.username}}'
          
          console.log(get_login_user);

          demo.initChartist();

          $.notify({
              icon: 'fa fa-user',
              message: "Welcome to My site,"+get_login_user

            },{
                type: 'info',
                timer: 4000
            });

      });

{% endblock %}

src/templates/dashboard/employee_app.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}


 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 <!-- width:200px; --><!-- enabled -> removes box responsiveness : avoid this -->
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #60a0b3 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#60a0b3;
}





{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	<section class="row">
	            		<section class="col col-lg-12">
	            			<a href="{{request.META.HTTP_REFERER|escape}}" style="color:#c1c1c1;">back</a>
	            		</section>
            	</section>
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
                    <!-- <div class="container"> -->
                    <section class="row margin-bottom">
                    	<div class="container-fluid">
                    	<section class="col-lg-4 col-md-4 col-sm-12">
	            			<div class="employee-box sec-box">
	            				<a href="{% url 'dashboard:employees' %}">
	            				<span>Employees</span>
	            				</a>
	            				<span class="count-object">{{ all_employees.count }}</span> 
	            			</div>
            			</section>
	            		</div>
                    </section><!-- /row -->

                    <!-- </div> -->
                    <!-- Search form -->
					<div class="row" style="margin-bottom: 2.2rem;margin-top: 3rem;">
					 <div class="">
					  <div class="col-lg-12">

					  	<form action="" method="GET">
						    <div class="input-group">
						      <span class="input-group-btn">
						        <button class="btn btn-default" id = "stylebutton" type="button">Search</button>
						      </span>
						      <input type="search" value="{{request.GET.search}}" name="search" class="form-control" placeholder="Search by firstname,lastname...">
						    </div><!-- /input-group -->
					    </form>

					  </div><!-- /.col-lg-6 -->
					  </div>
					</div><!-- /.row -->
					<!-- /search form -->

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">ALL EMPLOYEES TABLE</h4>
                		</div>
                		<div class="container-fluid">
                			<div class="row">
                			</div>
                		</div>
                		<table class="table">
							  <thead>
							    <tr>
							      <th scope="col">Fullname</th>
							      <th scope="col">Role</th>
							      <th scope="col">Department</th>
							      <th scope="col">Salaire</th>
								<th scope="col">Actions</th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for employee in employee_list %}
							    <tr>
							      <td>{{ employee.user }}</td>
							      <td>{{ employee.role }}</td>
							      <td>{{ employee.department }}</td>
							      <td>{{ employee.salaire }} DH</td>
								  <td>
							      	<a href="{% url 'dashboard:employeeinfo' employee.id %}">
							      	    view
							      	</a>
							        <a href="{% url 'dashboard:edit' employee.id %}">
							       	edit
							        </a>
									<a href="{% url 'dashboard:delete' employee.id %}">
										delete
									 </a>
							      </td>
							    </tr>
							    {% endfor %}

							  </tbody>

						</table>
						<!-- Pagination -->
							  <div class="pagination">
							    <span class="step-links">
							        {% if employee_list.has_previous %}
							            <a href="?page=1">&laquo; first</a>
							            <a href="?page={{ employee_list.previous_page_number }}">previous</a>
							        {% endif %}

							        <span class="current">
							            Page {{ employee_list.number }} of {{ employee_list.paginator.num_pages }}.
							        </span>

							        {% if employee_list.has_next %}
							            <a href="?page={{ employee_list.next_page_number }}">next</a>
							            <a href="?page={{ employee_list.paginator.num_pages }}">last &raquo;</a>
							        {% endif %}
							    </span>
							</div>
						<!-- /pagination -->


					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}
/*create-user-button - handler*/

// $(document).ready(function(){

// var createuser = $('.create-user-model');
// createuser.on('click',function(){
// alert("who clicked me ?")

// });


// });

{% endblock %}
</script>