src/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/change-password/', views.changepassword, name='changepassword'),
    path('user/profile/view/', views.user_profile_view, name='userprofile'),


]

src/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),

    # Employee
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:id>/',
         views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',
         views.employee_edit_data, name='edit'),
    path('employee/profile/delete/<int:id>/',
         views.dashboard_employee_delete, name='delete'),
    # Departement
    path('departments/all/', views.dashboard_departments, name='departments'),
    path('department/create/', views.dashboard_department_create,
         name='departmentcreate'),
    path('department/edit/<int:id>/',
         views.dashboard_department_edit_data, name='departmentedit'),
    path('department/delete/<int:id>/',
         views.dashboard_department_delete, name='departmentdelete'),
    # Role
    path('roles/all/', views.dashboard_roles, name='roles'),
    path('role/create/', views.dashboard_role_create, name='rolecreate'),
    path('role/edit/<int:id>/', views.dashboard_role_edit_data, name='roleedit'),
    path('role/delete/<int:id>/', views.dashboard_role_delete, name='roledelete'),

    # Announcement
    path('announcements/all/', views.dashboard_announcements, name='announcements'),
    path('announcement/create/', views.dashboard_announcement_create,
         name='announcementcreate'),
    path('announcement/edit/<int:id>/',
         views.dashboard_announcement_edit_data, name='announcementedit'),
    path('announcement/delete/<int:id>/',
         views.dashboard_announcement_delete, name='announcementdelete'),
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views


urlpatterns = [
    # change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('admin/', admin.site.urls),
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'PFA ADMINISTRATION'

src/employee/models.py
import datetime
from doctest import FAIL_FAST
from django.db import models
from employee.managers import EmployeeManager
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext as _
from django.contrib.auth.models import User


class Role(models.Model):
    '''
        Role Table eg. Staff,Manager,H.R ...
    '''
    name = models.CharField(max_length=125)
    description = models.CharField(max_length=125, null=True, blank=True)

    created = models.DateTimeField(
        verbose_name=_('Created'), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'), auto_now=True)

    class Meta:
        verbose_name = _('Role')
        verbose_name_plural = _('Roles')
        ordering = ['name', 'created']

    def __str__(self):
        return self.name


class Department(models.Model):
    '''
     Department Employee belongs to. eg. Transport, Engineering.
    '''
    name = models.CharField(max_length=125)
    description = models.CharField(max_length=125, null=True, blank=True)

    created = models.DateTimeField(
        verbose_name=_('Created'), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'), auto_now=True)

    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')
        ordering = ['name', 'created']

    def __str__(self):
        return self.name


class Employee(models.Model):
    MALE = 'male'
    FEMALE = 'female'
    OTHER = 'other'
    NOT_KNOWN = 'Not Known'

    GENDER = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other'),
        (NOT_KNOWN, 'Not Known'),
    )

    # PERSONAL DATA
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    image = models.FileField(_('Profile Image'), upload_to='profiles', default='default.png', blank=True,
                             null=True, help_text='upload image size less than 2.0MB')  # work on path username-date/image
    firstname = models.CharField(
        _('Firstname'), max_length=125, null=False, blank=False)
    lastname = models.CharField(
        _('Lastname'), max_length=125, null=False, blank=False)
    sex = models.CharField(_('Gender'), max_length=10,
                           default=MALE, choices=GENDER, blank=False)
    email = models.CharField(
        _('Email (optional)'), max_length=255, default=None, blank=True, null=True)
    tel = PhoneNumberField(default='+212000000000', null=False, blank=False,
                           verbose_name='Phone Number (Example +212000000000)', help_text='Enter number with Country Code Eg. +212000000000')
    bio = models.CharField(_('Bio'), help_text='your biography,tell me something about yourself eg. i love working ...',
                           max_length=255, default='', null=True, blank=True)
    birthday = models.DateField(_('Birthday'), blank=False, null=False)

    cinnumber = models.CharField(
        _('CIN Number'), max_length=30, null=True, blank=True)
    # COMPANY DATA
    department = models.ForeignKey(Department, verbose_name=_(
        'Department'), on_delete=models.SET_NULL, null=True, default=None)
    role = models.ForeignKey(Role, verbose_name=_(
        'Role'), on_delete=models.SET_NULL, null=True, default=None)
    startdate = models.DateField(
        _('Employement Date'), help_text='date of employement', blank=False, null=True)
    salaire = models.DecimalField(
        _('Salaire'), max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(verbose_name=_(
        'Created'), auto_now_add=True, null=True)
    updated = models.DateTimeField(
        verbose_name=_('Updated'), auto_now=True, null=True)

    # PLUG MANAGERS
    objects = EmployeeManager()

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        ordering = ['-created']

    def __str__(self):
        return self.get_full_name

    @property
    def get_age(self):
        current_year = datetime.date.today().year
        dateofbirth_year = self.birthday.year
        if dateofbirth_year:
            return current_year - dateofbirth_year
        return


class Announcement(models.Model):
    name = models.CharField(max_length=125)
    bio = models.CharField(max_length=255, default='', null=True, blank=True)

    created = models.DateTimeField(
        verbose_name=_('Created'), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'), auto_now=True)

    class Meta:
        verbose_name = _('Announcement')
        verbose_name_plural = _('Announcements')
        ordering = ['name', 'created']

    def __str__(self):
        return self.name

src/templates/_layout.html
{% load static %}

{% load humanize %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Dashboard | {% block title %} {{ title }} {% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Mike Edward <Fullstack Developer/>,mail - edward.mike.anaryo@gmail.com">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>


    <style type="text/css">

        .title-h3{
        font-weight: bold;
        font-variant: petite-caps;
    }


     .sidebar{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); 
     transition: all 400ms ease-in;
    }
    
    .sidebar:hover{
        -webkit-box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    }


    .shadow{
        box-shadow:0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     }

     a.simple-text{
        font-family: 'Russo One', sans-serif;
     }

      a.simple-text > span{
        font-size: 13px !important;
      }

      .logo a{
        font-family: 'Luckiest Guy', cursive;
      }

    .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px;
        font-family: 'Luckiest Guy', cursive;
    }


    tr td{
        font-variant: petite-caps;
    }

    {% block stylesheet %}
     
     
    {% endblock %}
    </style>

<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image="{% static 'img/sidebar-1.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">

            <ul class="nav">
                {% if request.user.is_superuser and request.user.is_staff %}

                <li class="active">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:employees' %}">
                        <i class="pe-7s-users"></i>
                        <p>Employee</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:departments' %}">
                        <i class="pe-7s-photo-gallery"></i>
                        <p>Departments</p>
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'dashboard:announcements' %}">
                        <i class="pe-7s-ribbon"></i>
                        <p>Annoucements</p>
                    </a>
                </li>
            </ul>
    	</div>


    </div>

    <div class="main-panel">
    <!--EVERY APP DEFINES ITS ROUTES  -->
    {% block navheader %}
        {% include 'includes/navheader_default.html' %}
    {% endblock %}
    <!-- NAVHEADER -->       

        
    <!--CONTENTS-->
    {% block content %}
    <section class="content">
        <section class="container-fluid">
                


        </section> <!-- /container -->           
     </section>
    {% endblock %}
    <!--/CONTENTS-->
        
    </div>
</div>


</body>



    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'js/demo.js' %}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        {% block extrajs%}

 

        {% endblock %}
    </script>

<script type="text/javascript">


    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.prev-holder .prev-avatar').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    
    $(document).ready(function(){

        $('.refresh-page').click(function(){
            /*Script refreshes the page*/
            console.log('refresh page clicked !!!');
            location.reload(true);

        });


        $( "#id_birthday,#id_dateissued,#id_startdate,#id_enddate" ).datepicker({
            dateFormat: 'yy-mm-dd'
        });


    });
    
	</script>

</html>

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>welcome page</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <!-- Bootstrap core CSS     -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alice" rel="stylesheet">
  



</head>
<body>

    <style type="text/css">
        body{
          position: relative;
          background-image: url('https://i.ibb.co/xhPX6mT/2053132.jpg');

        }

        
        a{
                font-variant: petite-caps;
                font-weight: 100;
                font-size: 16px;
        }


        .navbar-brand{
          font-variant: petite-caps;
          font-family: 'Luckiest Guy', cursive;
          font-weight: 600;
          font-size: 3.1rem;
          color: #e4a530;
          text-shadow:1px 2px 1px rgba(0,0,0,0.2);

        }


        h2{
          font-family: 'Alice', serif;
          color: gold;
          font-size: 4.9rem;


        }



        p{
          font-variant: small-caps;
          color: #cecece;

        }

        p span{
          color: #a5a5a5;
          font-weight: bold;
        }

        span.icon{
          font-size: 15px;
        }

        .content{
          position: relative;
          height: 100vh;
        }

        .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px !important;
        font-family: 'Luckiest Guy', cursive;
        }

        .back-link{
          color: #fff;
          font-size: 2.6rem;
          font-weight: 900;
          transition: all 400ms ease-in-out;
        }

        .back-link:hover{
          color: #fff;
          font-size: 2.8rem;
          transition: all 400ms ease-in-out;
        }

        .container-centered-items{
          position: absolute;
          top: 50%;
          left: 0;
          right: 0;
        }
        img {
          border-radius: 50%;
          width: 80px;
          margin-left: 5px;
        }
        .navbar-default .navbar-nav>li>a {
          margin-top: 12px;
          color: #777;
      }

    </style>

    <!--CONTENTS-->
 
    <section class="content">
            <!-- Navigation -->
                <nav class="navbar navbar-default ">
                      <div class="container-fluid test">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <a href="{% url 'home' %}"> <img src="{% static 'img/logo.jpeg' %}" alt="Avatar"> </a>
                          {% comment %} <span class="navbar-brand">PFA</span> {% endcomment %}
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                          <ul class="nav navbar-nav navbar-right">
                            <li>
                               <a class="mt-3" href="{% url 'accounts:login' %}">Login</a></li>
                          </ul>
                        </div><!-- /.navbar-collapse -->
                      </div><!-- /.container-fluid -->
                </nav>
            <!-- /Naivagtion -->

            <div class="container-fluid container-centered-items">
                <section class="row">
                  <section class="">
                     <section class="col col-lg-12 text-center">
                        <div class="center-me-please">
                            <h2> Human Resource Management </h2>
                        </div>
                     </section>
                  </section>
              </section>
            </div>
     </section> <!-- /content -->
    <div>
       {% if request.user.is_authenticated %}
                    <p style="position: absolute;bottom: 0;"><a href="{{request.META.HTTP_REFERER|escape}}" class="back-link" title="back to previous page"><i class="pe-7s-back-2"></i></a></p>
       {% endif %}
    </div>

</body>

    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
  


	<script type="text/javascript">
  
  
	</script>
 

</html>