src/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/change-password/', views.changepassword, name='changepassword'),
    path('user/profile/view/', views.user_profile_view, name='userprofile'),


]

src/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),

    # Employee
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:id>/',
         views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',
         views.employee_edit_data, name='edit'),
    path('employee/profile/delete/<int:id>/',
         views.dashboard_employee_delete, name='delete'),
    # Departement
    path('departments/all/', views.dashboard_departments, name='departments'),
    path('department/create/', views.dashboard_department_create,
         name='departmentcreate'),
    path('department/edit/<int:id>/',
         views.dashboard_department_edit_data, name='departmentedit'),
    path('department/delete/<int:id>/',
         views.dashboard_department_delete, name='departmentdelete'),
    # Role
    path('roles/all/', views.dashboard_roles, name='roles'),
    path('role/create/', views.dashboard_role_create, name='rolecreate'),
    path('role/edit/<int:id>/', views.dashboard_role_edit_data, name='roleedit'),
    path('role/delete/<int:id>/', views.dashboard_role_delete, name='roledelete'),

    # Announcement
    path('announcements/all/', views.dashboard_announcements, name='announcements'),
    path('announcement/create/', views.dashboard_announcement_create,
         name='announcementcreate'),
    path('announcement/edit/<int:id>/',
         views.dashboard_announcement_edit_data, name='announcementedit'),
    path('announcement/delete/<int:id>/',
         views.dashboard_announcement_delete, name='announcementdelete'),
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .import views


urlpatterns = [
    # change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('admin/', admin.site.urls),
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'PFA ADMINISTRATION'

src/templates/includes/navheader_default.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=""></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                         <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                                {% endif %}
                                <li><a href="{% url 'accounts:userprofile' %}">Profile</a></li>
                                <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                              </ul>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>

src/templates/includes/navheader_employee_app.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed shadow">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
                                <p class="hidden-lg hidden-md"> </p>
                            </a>
                        </li>
                        {% if request.user.is_superuser and request.user.is_staff %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Employee
                                        <b class="caret"></b>
                                    </p>
                              </a>
                              <ul class="dropdown-menu">
                                <li class="divider"></li>
                                <li><a href="{% url 'dashboard:employeecreate' %}">Add Employee</a></li>
                                <li><a href="{% url 'dashboard:employees' %}">All Employees</a></li>
                                <li class="divider"></li>
                              </ul>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                  <p>
                                      Departement
                                      <b class="caret"></b>
                                  </p>
                            </a>
                            <ul class="dropdown-menu">
                            <li class="divider"></li>
                              <li><a href="{% url 'dashboard:departmentcreate' %}">Add Departement</a></li>
                              <li><a href="{% url 'dashboard:departments' %}">All Departement</a></li>
                              <li class="divider"></li>
                            </ul>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">
                              <p>
                                  Role
                                  <b class="caret"></b>
                              </p>
                        </a>
                        <ul class="dropdown-menu">
                        <li class="divider"></li>
                          <li><a href="{% url 'dashboard:rolecreate' %}">Add Role</a></li>
                          <li><a href="{% url 'dashboard:roles' %}">All Roles</a></li>
                          <li class="divider"></li>
                        </ul>
                  </li>
                  <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                          <p>
                              Announcement
                              <b class="caret"></b>
                          </p>
                    </a>
                    <ul class="dropdown-menu">
                    <li class="divider"></li>
                      <li><a href="{% url 'dashboard:announcementcreate' %}">Add Announcement</a></li>
                      <li><a href="{% url 'dashboard:announcements' %}">All Announcements</a></li>
                      <li class="divider"></li>
                    </ul>
              </li>   
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle refresh-page" data-toggle="dropdown" title="refresh current page">
                                    <i class="pe-7s-refresh-2"></i>
                                    <b class="hidden-lg hidden-md"></b>
                                    <p class="hidden-lg hidden-md">
                                         refresh
                                    
                                    </p>
                              </a>
                        </li>

                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                                {% endif %}
                                <li><a href="{% url 'accounts:userprofile' %}">Profile</a></li>
                                <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                                <!-- <li class="divider"></li>
                                <li><a href="">Settings</a></li> -->
                              </ul>
                        </li>

                        <li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>